<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>Novolis.Physics.TestSupport</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Novolis.Math.Geometry" />
    <ProjectReference Include="..\..\src\Novolis.Physics.Orbits\Novolis.Physics.Orbits.csproj" />
  </ItemGroup>

</Project>
